<?php
/**
 * ProSEOMaster - 301 Redirect Manager
 *
 * Manages 301 redirects for:
 * - Old URLs to new URLs
 * - Deleted products/categories
 * - URL structure changes
 * - Import/Export CSV functionality
 *
 * @author      Michele Pietrafesa
 * @copyright   2024
 * @license     MIT
 * @version     1.0.0
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

class ProSEOMasterRedirects
{
    /** @var Context */
    protected $context;

    /** @var string Table name */
    protected $table = 'proseomaster_redirects';

    /** @var int Shop ID for multi-store support */
    protected $idShop;

    public function __construct($idShop = null)
    {
        $this->context = Context::getContext();
        $this->idShop = $idShop !== null ? (int) $idShop : (int) Context::getContext()->shop->id;
    }

    /**
     * Set shop ID for multi-store operations
     * @param int $idShop
     */
    public function setShopId($idShop)
    {
        $this->idShop = (int) $idShop;
    }

    /**
     * Get current shop ID
     * @return int
     */
    public function getShopId()
    {
        return $this->idShop;
    }

    /**
     * Install database table
     * @return bool
     */
    public function install()
    {
        $sql = 'CREATE TABLE IF NOT EXISTS `' . _DB_PREFIX_ . $this->table . '` (
            `id_redirect` int(11) unsigned NOT NULL AUTO_INCREMENT,
            `id_shop` int(11) unsigned NOT NULL DEFAULT 1,
            `old_url` varchar(512) NOT NULL,
            `new_url` varchar(512) NOT NULL,
            `redirect_type` int(3) NOT NULL DEFAULT 301,
            `hits` int(11) unsigned NOT NULL DEFAULT 0,
            `last_hit` datetime DEFAULT NULL,
            `active` tinyint(1) NOT NULL DEFAULT 1,
            `auto_generated` tinyint(1) NOT NULL DEFAULT 0,
            `date_add` datetime NOT NULL,
            `date_upd` datetime NOT NULL,
            PRIMARY KEY (`id_redirect`),
            KEY `old_url` (`old_url`(255)),
            KEY `id_shop` (`id_shop`),
            KEY `active` (`active`)
        ) ENGINE=' . _MYSQL_ENGINE_ . ' DEFAULT CHARSET=utf8mb4;';

        return Db::getInstance()->execute($sql);
    }

    /**
     * Uninstall database table
     * @return bool
     */
    public function uninstall()
    {
        return Db::getInstance()->execute('DROP TABLE IF EXISTS `' . _DB_PREFIX_ . $this->table . '`');
    }

    /**
     * Add a new redirect
     * @param string $oldUrl
     * @param string $newUrl
     * @param int $redirectType
     * @param bool $autoGenerated
     * @return bool|int
     */
    public function addRedirect($oldUrl, $newUrl, $redirectType = 301, $autoGenerated = false)
    {
        // Normalize URLs
        $oldUrl = $this->normalizeUrl($oldUrl);
        $newUrl = $this->normalizeUrl($newUrl);

        // Check if redirect already exists
        if ($this->redirectExists($oldUrl)) {
            return $this->updateRedirect($oldUrl, $newUrl, $redirectType);
        }

        // Prevent redirect loops
        if ($oldUrl === $newUrl) {
            return false;
        }

        $now = date('Y-m-d H:i:s');

        $result = Db::getInstance()->insert($this->table, array(
            'id_shop' => (int) $this->idShop,
            'old_url' => pSQL($oldUrl),
            'new_url' => pSQL($newUrl),
            'redirect_type' => (int) $redirectType,
            'hits' => 0,
            'last_hit' => null,
            'active' => 1,
            'auto_generated' => (int) $autoGenerated,
            'date_add' => $now,
            'date_upd' => $now,
        ));

        if ($result) {
            return (int) Db::getInstance()->insertId();
        }

        return false;
    }

    /**
     * Update existing redirect
     * @param string $oldUrl
     * @param string $newUrl
     * @param int $redirectType
     * @return bool
     */
    public function updateRedirect($oldUrl, $newUrl, $redirectType = 301)
    {
        $oldUrl = $this->normalizeUrl($oldUrl);
        $newUrl = $this->normalizeUrl($newUrl);

        return Db::getInstance()->update($this->table, array(
            'new_url' => pSQL($newUrl),
            'redirect_type' => (int) $redirectType,
            'date_upd' => date('Y-m-d H:i:s'),
        ), 'old_url = "' . pSQL($oldUrl) . '" AND id_shop = ' . (int) $this->idShop);
    }

    /**
     * Delete a redirect
     * @param int $idRedirect
     * @return bool
     */
    public function deleteRedirect($idRedirect)
    {
        return Db::getInstance()->delete($this->table, 'id_redirect = ' . (int) $idRedirect);
    }

    /**
     * Check if redirect exists
     * @param string $oldUrl
     * @return bool
     */
    public function redirectExists($oldUrl)
    {
        $oldUrl = $this->normalizeUrl($oldUrl);

        return (bool) Db::getInstance()->getValue(
            'SELECT COUNT(*) FROM `' . _DB_PREFIX_ . $this->table . '`
             WHERE old_url = "' . pSQL($oldUrl) . '"
             AND id_shop = ' . (int) $this->idShop
        );
    }

    /**
     * Get redirect for URL
     * @param string $url
     * @return array|false
     */
    public function getRedirect($url)
    {
        $url = $this->normalizeUrl($url);

        $redirect = Db::getInstance()->getRow(
            'SELECT * FROM `' . _DB_PREFIX_ . $this->table . '`
             WHERE old_url = "' . pSQL($url) . '"
             AND id_shop = ' . (int) $this->idShop . '
             AND active = 1'
        );

        if ($redirect) {
            // Update hit counter
            $this->incrementHits($redirect['id_redirect']);
            return $redirect;
        }

        return false;
    }

    /**
     * Increment hit counter for redirect
     * @param int $idRedirect
     * @return bool
     */
    protected function incrementHits($idRedirect)
    {
        return Db::getInstance()->execute(
            'UPDATE `' . _DB_PREFIX_ . $this->table . '`
             SET hits = hits + 1, last_hit = NOW()
             WHERE id_redirect = ' . (int) $idRedirect
        );
    }

    /**
     * Get all redirects
     * @param bool $activeOnly
     * @param int $limit
     * @param int $offset
     * @return array
     */
    public function getAllRedirects($activeOnly = false, $limit = 100, $offset = 0)
    {
        $sql = 'SELECT * FROM `' . _DB_PREFIX_ . $this->table . '`
                WHERE id_shop = ' . (int) $this->idShop;

        if ($activeOnly) {
            $sql .= ' AND active = 1';
        }

        $sql .= ' ORDER BY date_add DESC';
        $sql .= ' LIMIT ' . (int) $offset . ', ' . (int) $limit;

        return Db::getInstance()->executeS($sql);
    }

    /**
     * Get total redirect count
     * @param bool $activeOnly
     * @return int
     */
    public function getRedirectCount($activeOnly = false)
    {
        $sql = 'SELECT COUNT(*) FROM `' . _DB_PREFIX_ . $this->table . '`
                WHERE id_shop = ' . (int) $this->idShop;

        if ($activeOnly) {
            $sql .= ' AND active = 1';
        }

        return (int) Db::getInstance()->getValue($sql);
    }

    /**
     * Toggle redirect active status
     * @param int $idRedirect
     * @return bool
     */
    public function toggleActive($idRedirect)
    {
        return Db::getInstance()->execute(
            'UPDATE `' . _DB_PREFIX_ . $this->table . '`
             SET active = NOT active, date_upd = NOW()
             WHERE id_redirect = ' . (int) $idRedirect
        );
    }

    /**
     * Normalize URL for comparison
     * @param string $url
     * @return string
     */
    protected function normalizeUrl($url)
    {
        // Remove domain if present
        $parsed = parse_url($url);
        $path = isset($parsed['path']) ? $parsed['path'] : $url;

        // Remove leading/trailing slashes
        $path = trim($path, '/');

        // Remove query string for matching (optional)
        // $path = strtok($path, '?');

        return '/' . $path;
    }

    /**
     * Import redirects from CSV
     * @param string $csvContent
     * @return array Results with success/error counts
     */
    public function importFromCsv($csvContent)
    {
        $results = array(
            'success' => 0,
            'errors' => 0,
            'skipped' => 0,
            'messages' => array(),
        );

        $lines = explode("\n", $csvContent);

        foreach ($lines as $lineNum => $line) {
            $line = trim($line);

            // Skip empty lines and header
            if (empty($line) || $lineNum === 0 && strpos(strtolower($line), 'old') !== false) {
                continue;
            }

            $parts = str_getcsv($line);

            if (count($parts) < 2) {
                $results['errors']++;
                $results['messages'][] = 'Line ' . ($lineNum + 1) . ': Invalid format';
                continue;
            }

            $oldUrl = trim($parts[0]);
            $newUrl = trim($parts[1]);
            $redirectType = isset($parts[2]) ? (int) trim($parts[2]) : 301;

            if (empty($oldUrl) || empty($newUrl)) {
                $results['skipped']++;
                continue;
            }

            if ($this->addRedirect($oldUrl, $newUrl, $redirectType)) {
                $results['success']++;
            } else {
                $results['errors']++;
            }
        }

        return $results;
    }

    /**
     * Export redirects to CSV
     * @return string CSV content
     */
    public function exportToCsv()
    {
        $redirects = $this->getAllRedirects(false, 10000, 0);

        $csv = "old_url,new_url,redirect_type,hits,last_hit,active,date_add\n";

        foreach ($redirects as $redirect) {
            $csv .= '"' . $redirect['old_url'] . '",';
            $csv .= '"' . $redirect['new_url'] . '",';
            $csv .= $redirect['redirect_type'] . ',';
            $csv .= $redirect['hits'] . ',';
            $csv .= '"' . ($redirect['last_hit'] ? $redirect['last_hit'] : '') . '",';
            $csv .= $redirect['active'] . ',';
            $csv .= '"' . $redirect['date_add'] . '"' . "\n";
        }

        return $csv;
    }

    /**
     * Find potential redirects for 404 pages
     * Suggests similar URLs based on the requested URL
     * @param string $requestedUrl
     * @return array Suggestions
     */
    public function findSuggestions($requestedUrl)
    {
        $suggestions = array();
        $requestedUrl = $this->normalizeUrl($requestedUrl);

        // Extract potential product/category reference from URL
        $parts = explode('/', trim($requestedUrl, '/'));
        $lastPart = end($parts);

        // Remove common suffixes
        $lastPart = preg_replace('/\.(html?|php)$/i', '', $lastPart);
        $lastPart = preg_replace('/-\d+$/', '', $lastPart); // Remove ID suffix

        // Escape LIKE wildcard characters to prevent injection
        $escapedPart = str_replace(array('%', '_'), array('\\%', '\\_'), $lastPart);

        // Search for similar products
        $productSearch = Db::getInstance()->executeS(
            'SELECT p.id_product, pl.name, pl.link_rewrite
             FROM ' . _DB_PREFIX_ . 'product p
             INNER JOIN ' . _DB_PREFIX_ . 'product_lang pl ON p.id_product = pl.id_product
             INNER JOIN ' . _DB_PREFIX_ . 'product_shop ps ON p.id_product = ps.id_product
             WHERE pl.id_lang = ' . (int) $this->context->language->id . '
             AND ps.id_shop = ' . (int) $this->idShop . '
             AND ps.active = 1
             AND (pl.link_rewrite LIKE "%' . pSQL($escapedPart) . '%" OR pl.name LIKE "%' . pSQL($escapedPart) . '%")
             LIMIT 5'
        );

        foreach ($productSearch as $product) {
            $suggestions[] = array(
                'type' => 'product',
                'name' => $product['name'],
                'url' => $this->context->link->getProductLink($product['id_product']),
            );
        }

        // Search for similar categories
        $categorySearch = Db::getInstance()->executeS(
            'SELECT c.id_category, cl.name, cl.link_rewrite
             FROM ' . _DB_PREFIX_ . 'category c
             INNER JOIN ' . _DB_PREFIX_ . 'category_lang cl ON c.id_category = cl.id_category
             INNER JOIN ' . _DB_PREFIX_ . 'category_shop cs ON c.id_category = cs.id_category
             WHERE cl.id_lang = ' . (int) $this->context->language->id . '
             AND cs.id_shop = ' . (int) $this->idShop . '
             AND c.active = 1
             AND (cl.link_rewrite LIKE "%' . pSQL($escapedPart) . '%" OR cl.name LIKE "%' . pSQL($escapedPart) . '%")
             LIMIT 5'
        );

        foreach ($categorySearch as $category) {
            $suggestions[] = array(
                'type' => 'category',
                'name' => $category['name'],
                'url' => $this->context->link->getCategoryLink($category['id_category']),
            );
        }

        return $suggestions;
    }

    /**
     * Auto-generate redirect when product is deleted
     * @param int $idProduct
     * @param int $idCategory Fallback category
     * @return bool
     */
    public function autoRedirectDeletedProduct($idProduct, $idCategory = null)
    {
        // Get old product URL before deletion
        $productUrl = $this->context->link->getProductLink($idProduct);
        $productPath = parse_url($productUrl, PHP_URL_PATH);

        // Determine new URL (category or home)
        if ($idCategory) {
            $newUrl = $this->context->link->getCategoryLink($idCategory);
        } else {
            $newUrl = $this->context->link->getPageLink('index');
        }

        return $this->addRedirect($productPath, $newUrl, 301, true);
    }

    /**
     * Auto-generate redirect when category is deleted
     * @param int $idCategory
     * @param int $idParentCategory Parent category
     * @return bool
     */
    public function autoRedirectDeletedCategory($idCategory, $idParentCategory = null)
    {
        // Get old category URL before deletion
        $categoryUrl = $this->context->link->getCategoryLink($idCategory);
        $categoryPath = parse_url($categoryUrl, PHP_URL_PATH);

        // Determine new URL (parent category or home)
        if ($idParentCategory && $idParentCategory > 2) {
            $newUrl = $this->context->link->getCategoryLink($idParentCategory);
        } else {
            $newUrl = $this->context->link->getPageLink('index');
        }

        return $this->addRedirect($categoryPath, $newUrl, 301, true);
    }

    /**
     * Process redirect on page not found
     * Should be called from a front controller override or hook
     * @return bool True if redirect was performed
     */
    public function processRedirect()
    {
        $requestUri = isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '';
        $redirect = $this->getRedirect($requestUri);

        if ($redirect) {
            $newUrl = $redirect['new_url'];

            // Make absolute URL if needed
            if (strpos($newUrl, 'http') !== 0) {
                $baseUrl = $this->context->link->getBaseLink();
                $newUrl = rtrim($baseUrl, '/') . $newUrl;
            }

            // Perform redirect
            header('HTTP/1.1 ' . $redirect['redirect_type'] . ' Moved Permanently');
            header('Location: ' . $newUrl);
            header('Connection: close');
            exit;
        }

        return false;
    }

    /**
     * Get redirect statistics
     * @return array
     */
    public function getStatistics()
    {
        $stats = array();

        // Total redirects
        $stats['total'] = $this->getRedirectCount(false);
        $stats['active'] = $this->getRedirectCount(true);

        // Total hits
        $stats['total_hits'] = (int) Db::getInstance()->getValue(
            'SELECT SUM(hits) FROM `' . _DB_PREFIX_ . $this->table . '`
             WHERE id_shop = ' . (int) $this->idShop
        );

        // Most used redirects
        $stats['top_redirects'] = Db::getInstance()->executeS(
            'SELECT old_url, new_url, hits FROM `' . _DB_PREFIX_ . $this->table . '`
             WHERE id_shop = ' . (int) $this->idShop . '
             AND active = 1
             ORDER BY hits DESC
             LIMIT 10'
        );

        // Auto-generated count
        $stats['auto_generated'] = (int) Db::getInstance()->getValue(
            'SELECT COUNT(*) FROM `' . _DB_PREFIX_ . $this->table . '`
             WHERE id_shop = ' . (int) $this->idShop . '
             AND auto_generated = 1'
        );

        return $stats;
    }

    /**
     * Get stats (alias for getStatistics)
     * @return array
     */
    public function getStats()
    {
        return $this->getStatistics();
    }

    /**
     * Clean old unused redirects
     * @param int $daysOld Remove redirects older than X days with 0 hits
     * @return int Number of deleted redirects
     */
    public function cleanOldRedirects($daysOld = 90)
    {
        $cutoffDate = date('Y-m-d H:i:s', strtotime("-{$daysOld} days"));

        $result = Db::getInstance()->execute(
            'DELETE FROM `' . _DB_PREFIX_ . $this->table . '`
             WHERE id_shop = ' . (int) $this->idShop . '
             AND hits = 0
             AND auto_generated = 1
             AND date_add < "' . pSQL($cutoffDate) . '"'
        );

        return $result ? Db::getInstance()->affectedRows() : 0;
    }
}
