<?php
/**
 * ProSEOMaster - Dynamic Robots.txt Manager
 *
 * Generates optimized robots.txt with:
 * - Smart crawl directives
 * - Proper sitemap references
 * - Crawl-delay for bots
 * - Blocking of low-value URLs
 *
 * @author      Michele Pietrafesa
 * @copyright   2024
 * @license     MIT
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

class ProSEOMasterRobots
{
    /** @var Context */
    protected $context;

    public function __construct()
    {
        $this->context = Context::getContext();
    }

    /**
     * Generate optimized robots.txt content
     * @return string
     */
    public function generateRobotsTxt()
    {
        $baseUrl = $this->context->link->getBaseLink();
        $lines = array();

        // Header comment
        $lines[] = '# Robots.txt generated by ProSEO Master';
        $lines[] = '# Last updated: ' . date('Y-m-d H:i:s');
        $lines[] = '';

        // Googlebot specific rules
        $lines[] = '# Googlebot';
        $lines[] = 'User-agent: Googlebot';
        $lines = array_merge($lines, $this->getCommonDisallows());
        $lines[] = '';

        // Googlebot-Image
        $lines[] = '# Googlebot Image';
        $lines[] = 'User-agent: Googlebot-Image';
        $lines[] = 'Disallow: /modules/';
        $lines[] = 'Disallow: /themes/';
        $lines[] = '';

        // Bingbot
        $lines[] = '# Bingbot';
        $lines[] = 'User-agent: Bingbot';
        $lines = array_merge($lines, $this->getCommonDisallows());
        $lines[] = 'Crawl-delay: 1';
        $lines[] = '';

        // All other bots
        $lines[] = '# All other robots';
        $lines[] = 'User-agent: *';
        $lines = array_merge($lines, $this->getCommonDisallows());
        $lines[] = 'Crawl-delay: 2';
        $lines[] = '';

        // Bad bots (block completely)
        $lines[] = '# Block bad bots';
        $badBots = array(
            'AhrefsBot',
            'SemrushBot',
            'MJ12bot',
            'DotBot',
            'BLEXBot',
            'SearchmetricsBot',
        );
        foreach ($badBots as $bot) {
            $lines[] = 'User-agent: ' . $bot;
            $lines[] = 'Disallow: /';
            $lines[] = '';
        }

        // Sitemap
        $lines[] = '# Sitemap';
        $lines[] = 'Sitemap: ' . $baseUrl . 'sitemap.xml';
        $lines[] = '';

        // Host directive (for Yandex)
        $lines[] = '# Host';
        $lines[] = 'Host: ' . parse_url($baseUrl, PHP_URL_HOST);

        return implode("\n", $lines);
    }

    /**
     * Get common disallow rules
     * @return array
     */
    protected function getCommonDisallows()
    {
        $rules = array();

        // Cart and checkout
        $rules[] = 'Disallow: /*?add=';
        $rules[] = 'Disallow: /*?delete=';
        $rules[] = 'Disallow: /*&add=';
        $rules[] = 'Disallow: /*&delete=';
        $rules[] = 'Disallow: /carrello';
        $rules[] = 'Disallow: /cart';
        $rules[] = 'Disallow: /panier';
        $rules[] = 'Disallow: /ordine';
        $rules[] = 'Disallow: /order';
        $rules[] = 'Disallow: /commande';
        $rules[] = 'Disallow: /checkout';

        // User account
        $rules[] = 'Disallow: /my-account';
        $rules[] = 'Disallow: /mio-account';
        $rules[] = 'Disallow: /mon-compte';
        $rules[] = 'Disallow: /identity';
        $rules[] = 'Disallow: /addresses';
        $rules[] = 'Disallow: /history';
        $rules[] = 'Disallow: /order-slip';
        $rules[] = 'Disallow: /credit-slip';
        $rules[] = 'Disallow: /discount';

        // Login/Registration
        $rules[] = 'Disallow: /login';
        $rules[] = 'Disallow: /authentication';
        $rules[] = 'Disallow: /registration';
        $rules[] = 'Disallow: /password-recovery';
        $rules[] = 'Disallow: /guest-tracking';

        // Search with parameters
        $rules[] = 'Disallow: /*?q=';
        $rules[] = 'Disallow: /*?s=';
        $rules[] = 'Disallow: /*&q=';
        $rules[] = 'Disallow: /*&s=';
        $rules[] = 'Disallow: /cerca';
        $rules[] = 'Disallow: /search';
        $rules[] = 'Disallow: /recherche';

        // Faceted navigation / Filters (critical for SEO)
        $rules[] = 'Disallow: /*?order=';
        $rules[] = 'Disallow: /*&order=';
        $rules[] = 'Disallow: /*?orderby=';
        $rules[] = 'Disallow: /*&orderby=';
        $rules[] = 'Disallow: /*?orderway=';
        $rules[] = 'Disallow: /*&orderway=';
        $rules[] = 'Disallow: /*?n=';
        $rules[] = 'Disallow: /*&n=';
        $rules[] = 'Disallow: /*?p=';
        $rules[] = 'Disallow: /*?resultsPerPage=';
        $rules[] = 'Disallow: /*&resultsPerPage=';

        // Product comparison
        $rules[] = 'Disallow: /compare';
        $rules[] = 'Disallow: /products-comparison';

        // Core directories
        $rules[] = 'Disallow: /classes/';
        $rules[] = 'Disallow: /config/';
        $rules[] = 'Disallow: /controllers/';
        $rules[] = 'Disallow: /download/';
        $rules[] = 'Disallow: /mails/';
        $rules[] = 'Disallow: /modules/*/classes/';
        $rules[] = 'Disallow: /modules/*/controllers/';
        $rules[] = 'Disallow: /modules/*/mails/';
        $rules[] = 'Disallow: /override/';
        $rules[] = 'Disallow: /src/';
        $rules[] = 'Disallow: /tools/';
        $rules[] = 'Disallow: /translations/';
        $rules[] = 'Disallow: /upload/';
        $rules[] = 'Disallow: /var/';
        $rules[] = 'Disallow: /vendor/';
        $rules[] = 'Disallow: /webservice/';

        // Admin
        $rules[] = 'Disallow: /admin*/';
        $rules[] = 'Disallow: /backoffice/';

        // Install
        $rules[] = 'Disallow: /install/';
        $rules[] = 'Disallow: /install-dev/';

        // PDF and exports
        $rules[] = 'Disallow: /pdf/';
        $rules[] = 'Disallow: /*?content_only=';

        // Tracking parameters
        $rules[] = 'Disallow: /*?utm_';
        $rules[] = 'Disallow: /*&utm_';
        $rules[] = 'Disallow: /*?gclid=';
        $rules[] = 'Disallow: /*&gclid=';
        $rules[] = 'Disallow: /*?fbclid=';
        $rules[] = 'Disallow: /*&fbclid=';

        // Ajax and API
        $rules[] = 'Disallow: /*?ajax=';
        $rules[] = 'Disallow: /*&ajax=';
        $rules[] = 'Disallow: /*?action=';
        $rules[] = 'Disallow: /*&action=';
        $rules[] = 'Disallow: /*?controller=';
        $rules[] = 'Disallow: /*&controller=';
        $rules[] = 'Disallow: /*?fc=module';

        // Allow important files
        $rules[] = 'Allow: /modules/*/img/';
        $rules[] = 'Allow: /modules/*/views/img/';
        $rules[] = 'Allow: /modules/*/views/css/';
        $rules[] = 'Allow: /modules/*/views/js/';
        $rules[] = 'Allow: /*.css';
        $rules[] = 'Allow: /*.js';
        $rules[] = 'Allow: /*.png';
        $rules[] = 'Allow: /*.jpg';
        $rules[] = 'Allow: /*.jpeg';
        $rules[] = 'Allow: /*.gif';
        $rules[] = 'Allow: /*.webp';
        $rules[] = 'Allow: /*.svg';

        return $rules;
    }

    /**
     * Save robots.txt file
     * @return bool
     */
    public function saveRobotsTxt()
    {
        try {
            $content = $this->generateRobotsTxt();
            $filepath = _PS_ROOT_DIR_ . '/robots.txt';

            // Check if directory is writable
            if (!is_writable(dirname($filepath))) {
                PrestaShopLogger::addLog(
                    'ProSEOMaster: Cannot write robots.txt - directory not writable',
                    3,
                    null,
                    'ProSEOMaster'
                );
                return false;
            }

            $result = file_put_contents($filepath, $content);

            if ($result === false) {
                PrestaShopLogger::addLog(
                    'ProSEOMaster: Failed to save robots.txt',
                    3,
                    null,
                    'ProSEOMaster'
                );
                return false;
            }

            return true;
        } catch (Exception $e) {
            PrestaShopLogger::addLog(
                'ProSEOMaster: robots.txt error - ' . $e->getMessage(),
                3,
                null,
                'ProSEOMaster'
            );
            return false;
        }
    }

    /**
     * Get current robots.txt content
     * @return string|null
     */
    public function getCurrentRobotsTxt()
    {
        try {
            $filepath = _PS_ROOT_DIR_ . '/robots.txt';

            if (file_exists($filepath) && is_readable($filepath)) {
                return file_get_contents($filepath);
            }

            return null;
        } catch (Exception $e) {
            PrestaShopLogger::addLog(
                'ProSEOMaster: Error reading robots.txt - ' . $e->getMessage(),
                2,
                null,
                'ProSEOMaster'
            );
            return null;
        }
    }

    /**
     * Backup current robots.txt
     * @return bool
     */
    public function backupRobotsTxt()
    {
        $filepath = _PS_ROOT_DIR_ . '/robots.txt';
        $backupPath = _PS_ROOT_DIR_ . '/robots.txt.backup.' . date('YmdHis');

        if (file_exists($filepath)) {
            return copy($filepath, $backupPath);
        }

        return true;
    }
}
